# Generated by Django 4.1.7 on 2023-03-17 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('Hos_id', models.AutoField(primary_key=True, serialize=False)),
                ('Hos_name', models.CharField(max_length=255)),
                ('Hos_address', models.CharField(max_length=255)),
                ('Hos_city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pat_id', models.AutoField(primary_key=True, serialize=False)),
                ('pat_name', models.CharField(max_length=255)),
                ('pat_diagnosis', models.CharField(max_length=255)),
                ('pat_address', models.CharField(max_length=255)),
                ('pat_hos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_patent', to='drf_task.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_exmaination', models.DateField(auto_now_add=True)),
                ('problem', models.CharField(max_length=255)),
                ('med_pat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical', to='drf_task.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=255)),
                ('qualifcation', models.CharField(max_length=255)),
                ('salary', models.PositiveIntegerField()),
                ('doc_hos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_doctor', to='drf_task.hospital')),
            ],
        ),
    ]
