# Generated by Django 4.1.7 on 2023-03-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Hos_pincode',
            field=models.IntegerField(default=337637, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='pat_email',
            field=models.EmailField(default='admin@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
