# Generated by Django 4.1.7 on 2023-03-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_task', '0004_patient_pat_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pat_email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
