# Generated by Django 4.1.7 on 2023-03-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_task', '0006_doctor_doc_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
