# Generated by Django 4.1.7 on 2023-03-20 13:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=255)),
                ('customer_address', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_department', models.CharField(max_length=255)),
                ('employee_address', models.CharField(max_length=255)),
                ('contact_add', models.PositiveIntegerField(default='+914434232322')),
            ],
            options={
                'verbose_name': 'Employees',
                'verbose_name_plural': 'Employees',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to='hotel_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('date_range', models.DateField()),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_reservation', to='hotel_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RoomClass',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_name', models.CharField(max_length=255)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_transaction', to='hotel_management.customer')),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_transaction', to='hotel_management.employees')),
                ('payment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='hotel_management.payment')),
                ('reservation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_transaction', to='hotel_management.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='RoomInformation',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roomclass_roominformation', to='hotel_management.roomclass')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roominformation_reservation', to='hotel_management.roominformation'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('date', models.DateField(auto_created=True)),
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('information', models.CharField(max_length=255)),
                ('transaction_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_report', to='hotel_management.transaction')),
            ],
        ),
    ]
